language: scala

jdk: openjdk11

scala:
  - 2.12.10
  - 2.13.1

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalafmt test:scalafmt scalafmtSbt && codecov
