language: scala

jdk: openjdk11

scala:
  - 2.12.8

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

install:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6) > /usr/local/bin/mill && chmod +x /usr/local/bin/mill'

script:
  - mill __.publishLocal